### ISSUE TITLE
User trophies

### ISSUE THREAD

**Issue by Chrysem** [vhin0210/PHP-PSNPublicTrophies#1]
Hello,

Your api is great but i think something is missing : to get the detail of the users's trophie on a specific game.

Is there a new method to check the user's trophie ?

Regards,

**Comment by vhin0210** [comment]
Thanks! Unfortunately, it's still under development. Will keep you posted.

**Comment by vhin0210** [comment]
Please use [1.1.1](https://github.com/vhin0210/PHP-PSNPublicTrophies/tree/1.1.1)

Please read the latest README.md on how to authenticate.
Once you authenticate, you can do something like this code:
```
$psnAuth = new \PSNPublicTrophiesLib\PSNPublicTrophiesAuth($psn_account_token);

$trophy = $psnAuth->getTrophy();
$gameTrophies = $trophy->GetGameTrophies($game_id);
```
