### ISSUE TITLE
Doesn't work anymore...

### ISSUE THREAD

**Issue by Reuns** [vhin0210/PHP-PSNPublicTrophies#2]
Hi,

Everything works perfectly since a few days... 
I think Sony change their method.

Will you update your class ?
Thanks
Reuns

**Comment by vhin0210** [comment]
Still trying to find out a workaround but looks like sony totally scrap this endpoint. Will keep you posted

**Comment by Reuns** [comment]
Nice !
Thanks and good luck.

**Comment by vhin0210** [comment]
I updated the library to use the authenticated way.
Please use [1.1.1](https://github.com/vhin0210/PHP-PSNPublicTrophies/tree/1.1.1)

Please read the latest README.md on how to authenticate
